# Generated by Django 3.1.5 on 2021-01-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210104_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='none', max_length=30, null=True),
        ),
    ]
