# Generated by Django 3.1.5 on 2021-01-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editorpick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='main3',
            field=models.BooleanField(default=False),
        ),
    ]
