# Generated by Django 3.1.5 on 2021-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210112_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textcontent',
            field=models.TextField(default='none', null=True),
        ),
    ]
