# Generated by Django 3.1.5 on 2021-01-13 14:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_thumbnail_1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blogimg/thumbnail'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumbnail_2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blogimg/thumbnail'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumbnail_3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blogimg/thumbnail'),
        ),
    ]
