# Generated by Django 3.1.5 on 2021-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210113_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
